In [1]:
import numpy as np

## DataTypes and Attributes

In [2]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [32]:
a2 = np.array([[1,2.0,3.3],
               [4,5,6.5]])
a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
               [[10,11,12],
               [13,14,15],
               [16,17,18]]])


In [33]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [34]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [35]:
a1.shape

(3,)

In [36]:
a2.shape

(2, 3)

In [37]:
a3.shape

(2, 3, 3)

In [38]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [39]:
 a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [40]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [42]:
# Create a DataFrame from a NumPy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating arrays

In [43]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [51]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [52]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [53]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [55]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[0, 4, 0, 6, 0],
       [4, 7, 6, 3, 3],
       [7, 5, 6, 9, 5]])

In [57]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.3023083 , 0.16734476, 0.7543458 ],
       [0.69534181, 0.35461272, 0.23736444],
       [0.72275387, 0.5736579 , 0.99809692],
       [0.76856235, 0.02956885, 0.6275565 ],
       [0.14115934, 0.17929553, 0.99068115]])

In [59]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.3882421 , 0.7517473 , 0.65093319],
       [0.85832062, 0.46065785, 0.36318911],
       [0.14620491, 0.93105886, 0.52037086],
       [0.02330327, 0.3308528 , 0.29858784],
       [0.39337787, 0.13894485, 0.01165771]])

In [72]:
# Pseudo-random numbers
np.random.seed(seed=5)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[3, 6, 6],
       [0, 9, 8],
       [4, 7, 0],
       [0, 7, 1],
       [5, 7, 0]])

## Viewing arrays and matrices

In [73]:
np.unique(random_array_4)

array([0, 1, 3, 4, 5, 6, 7, 8, 9])

In [74]:
a1[0]

1

In [75]:
a2[0]

array([1. , 2. , 3.3])

In [78]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [85]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [86]:
a3[:, :, :2]

array([[[ 1,  2],
        [ 4,  5],
        [ 7,  8]],

       [[10, 11],
        [13, 14],
        [16, 17]]])

## Manipulating & Comparing array

### Arithmetic

In [97]:
a1

array([1, 2, 3])

In [89]:
ones = np.ones(3)
a1 + ones

array([2., 3., 4.])

In [90]:
a1 - ones

array([0., 1., 2.])

In [91]:
a1 * ones

array([1., 2., 3.])

In [99]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [101]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

### Reshape and transpose array

In [102]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [103]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [111]:
a2_reshape = a2.reshape((2,3,1))

In [110]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [116]:
# Transpose
a2.shape

(2, 3)

In [114]:
a2.T.shape

(3, 2)

## Dot Product

In [121]:
np.random.seed(0)
mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(3,5))

mat1


array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [122]:
mat2

array([[6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4],
       [3, 0, 3, 5, 0]])

In [123]:
np.dot(mat1,mat2)

array([[ 39,  35,  44,  55,   5],
       [ 80,  84, 104, 132,  31],
       [ 49,  66,  67,  79,  23],
       [ 77,  91, 102, 125,  32],
       [ 91, 128, 123, 141,  40]])

## Numpy Images

In [133]:
from matplotlib.image import imread

panda = imread("panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [134]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)